name: horse_mat
isMaterial: true

####network#####
network: material
database_name: syn/horse
mesh: data/meshes/horse_shape-180000.ply
geo_model_path: data/model/horse_shape/model.pth

reg_diffuse_light: true
reg_diffuse_light_lambda: 0.1
reg_mat: true
shader_cfg:
  diffuse_sample_num: 512
  specular_sample_num: 256
  outer_light_version: direction
  light_exp_max: 5.0
  inner_light_exp_max: 5.0
  human_lights: false

######loss######
loss: ['nerf_render','mat_reg']
val_metric: ['mat_render']
key_metric_name: psnr

####dataset#####
train_dataset_type: dummy
dataset_dir: /home/riga/NeRF/nerf_data/GlossySynthetic           # !!!! change your dataset dir !!!!
train_dataset_cfg:
  database_name: syn/horse
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: syn/horse

####trainier####
optimizer_type: adam
lr_type: warm_up_cos
total_step: 100000
val_interval: 5000
save_interval: 500
train_log_step: 10

####relighting settings####
trans: true