name: grogu_scene001_shape

####network#####
network: shape
database_name: orb/grogu_scene001
nerfDataType: True
apply_occ_loss: true
occ_loss_step: 10000 # 20000
apply_mask_loss: true
clip_sample_variance: false
has_radiance_field: true
radiance_field_step: 20000
apply_gaussian_loss: true
gaussianLoss_step: 20000
predict_BG: false
isBGWhite: true
downsample_ratio: 0.25
alphaMask_thres: 0.00001
mul_length: 15

######loss######
loss: ['nerf_render','eikonal', 'std', 'init_sdf_reg','occ', 'Sparse', 'TV', 'mask', 'Gaussian']
val_metric: ['shape_render']
key_metric_name: psnr
eikonal_weight: 0.1
mask_loss_weight: 0.5
hessian_weight: 0.0005
gaussian_weight: 0.00001
sparse_weight: 0.1
sparse_ratio: [0.2, 0.2]
freeze_inv_s_step: 8000 # 15000

####dataset#####
train_dataset_type: dummy
dataset_dir: /nerf_data/llff/blender_LDR          # !!!! change your dataset dir !!!!
train_dataset_cfg:
  database_name: orb/grogu_scene001
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: orb/grogu_scene001

####trainier####
optimizer_type: adam
lr_type: warm_up_cos
lr_cfg: {}
total_step: 180000
val_interval: 2500
save_interval: 1000
train_log_step: 20
N_voxel_init: 2097153 # 128**3 + 1
N_voxel_final: 134217729 # 512**3 + 1
step_ratio: 2.5
upsample_list: [20000, 40000]
update_AlphaMask_lst: [20000]
hessian_ratio: [0.1, 0.05]

###SDF setting###
sdf_n_comp: 36
sdf_dim: 256
app_dim: 128

###Mesh extraction###
blend_ratio: 0.8