name: horse_shape

####network#####
network: shape
database_name: syn/horse
split_manul: false
nerfDataType: false
apply_occ_loss: true
occ_loss_step: 10000 # 20000
apply_mask_loss: false
clip_sample_variance: false
has_radiance_field: true
radiance_field_step: 20000
apply_gaussian_loss: false
gaussianLoss_step: 20000
predict_BG: true
isBGWhite: false
downsample_ratio: 0.5
alphaMask_thres: 0.0001
mul_length: 0

######loss######
loss: ['nerf_render','eikonal', 'std', 'init_sdf_reg','occ', 'Sparse', 'TV', 'Hessian']
val_metric: ['shape_render']
key_metric_name: psnr
eikonal_weight: 0.1
hessian_weight: 0.0005
sparse_weight: 0.05


####dataset#####
train_dataset_type: dummy
dataset_dir: /home/riga/NeRF/nerf_data/GlossySynthetic           # !!!! change your dataset dir !!!!
train_dataset_cfg:
  database_name: syn/horse
  split_manul: false
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: syn/horse
      split_manul: false

####trainier####
optimizer_type: adam
lr_type: warm_up_cos
lr_cfg: {}
total_step: 180000
val_interval: 2500
save_interval: 1000
train_log_step: 20
N_voxel_init: 2097153 # 128**3 + 1
N_voxel_final: 134217729 # 512**3 + 1
upsample_list: [40000, 80000]
update_AlphaMask_lst: [40000, 80000]
hessian_ratio: [0.1, 0.05]

###SDF setting###
sdf_n_comp: 36
sdf_dim: 256
app_dim: 128

###Mesh extraction###
blend_ratio: 0.5